### ISSUE TITLE
Annotate R-square

### ISSUE THREAD

**Issue by IsadoraBM** [fsolt/dotwhisker#109]
Request to integrate way to state either manually or through broomExtra::tidy_parameters the R-squared of each model to show up in graph (on it or legend if more than one model is piped through).

**Comment by sammo3182** [comment]
Thank you for the request. We'll definitely think about that. Before that, though, you actually can add any statistics you want manually after creating the dotwhisker plot probably with `geom_text` or in the caption or even title. `dotwhisker` produces `ggplot` object allowing users to conduct further build-ups.

**Comment by sammo3182** [comment]
New update after three years😂 The function has been incorporated into the package since v. 0.8.1. Have a try and let me know if there is any questions. Thanks for the suggestion, again!

**Comment by IsadoraBM** [comment]
That's great! I still use dotwhisker and I had been implementing a chunky geom_text solution, can't wait to see what it looks like. BTW your vignette link is 404, maybe due to the new version refresh? 
![image](https://github.com/fsolt/dotwhisker/assets/26873609/b5f6d06a-8377-4f4c-9c9a-79d4f76fab3c)
