### ISSUE TITLE
add_bracket should calculate xloc rather than take it as an argument

### ISSUE THREAD

**Issue by fsolt** [fsolt/dotwhisker#11]

**Comment by fsolt** [comment]
overhang and fin_size are going to also need work to account for varying proportions of plots; constants only work for the plotsize I happened to be using

**Comment by sammo3182** [comment]
When I tried to run the example under add_bracket function, it failed with an error or unused argument "xloc = -29". When I deleted that argument, the produced plot seems not right...

**Comment by fsolt** [comment]
Yep: add_bracket remains very much a work in progress.  It'll be at least a day or two until I can get back to it, though.

**Comment by sammo3182** [comment]
Just tried the new add_bracket function. It works excellent and is easy to manipulate! A following issue is that it seems can only add one bracket to a dotplot. I tried to produce a parallel plot (Kastellec & Leoni 2007, 767), but it turns error when adding an additional bracket:
`Error in p + theme(plot.margin = unit(c(1, 1, 1, -1), "lines")) + ylab("") : 
  non-numeric argument to binary operator
In addition: Warning message:
In max(pd$y_ind) : no non-missing arguments to max; returning -Inf`
