### ISSUE TITLE
dwplot vs dw_plot

### ISSUE THREAD

**Issue by phargarten2** [fsolt/dotwhisker#111]
Thank you for making this package. Utilizing **broom** and **ggplot2** can create useful plots.
The documentation listed two functions to construct the plots: `dwplot` and `dw_plot`. Is there a difference between them? 
If there is a difference, which one should be used when?
The text in the documentation and the vignette only mentioned one `dwplot`.

**Comment by fsolt** [comment]
Thanks for your kind words, @phargarten2!  We're glad you find interplot useful.  To answer your question: there's no difference between the two: `dw_plot` is an alias for `dwplot`.
