### ISSUE TITLE
archived on CRAN?

### ISSUE THREAD

**Issue by bbolker** [fsolt/dotwhisker#115]
The [CRAN page](https://cran.r-project.org/web/packages/dotwhisker/index.html) says:

> Package ‘dotwhisker’ was removed from the CRAN repository.<br>
> ... <br>
> Archived on 2024-04-12 as requires archived package 'prediction'.

~~However, I can't for the life of me see where this dependence could come from. Neither the `DESCRIPTION` file of the last-archived version on CRAN, nor the version on github, seem to show any signs of importing `prediction` ... ?? I suppose there's a possibility of a recursive dependence, but in that case why wouldn't the direct dependence be reported?~~

Thanks to `r-package-devel`, I now know that this is through the dependence on the `margins` package. Short of (1) removing this functionality, (2) switching to the more active `marginaleffects` package, I don't see a fix other than waiting for the maintainer of the `prediction` package to resubmit to CRAN ...

```
Depends: R (>= 3.2.0), ggplot2 (>= 2.2.1),
Imports: grid, gtable, gridExtra, stats, parameters, performance,
        patchwork, margins, dplyr, stringr, ggstance, rlang, purrr
Suggests: ordinal, tibble, knitr, rmarkdown, broom
```

**Comment by LucieCBurgess** [comment]
Could this please be fixed as dotwhisker desperately needed for PhD thesis submission in 2 weeks ...!
Otherwise I need to go back to the older version and this becomes a rather problematic dependency issue. 
Very many thanks to the package authors if you are able to give this some attention.

**Comment by LucieCBurgess** [comment]
Version 0.7.4 nowhere to be seen - if the previous version could please be put back on CRAN that would help (unless this has the same dependency issue)

**Comment by bbolker** [comment]
This is really an "upstream" problem with the `prediction` package, i.e. you should comment [here](https://github.com/leeper/prediction/pull/56) or [here](https://github.com/leeper/prediction/issues/55). I did reach the maintainer of `prediction` by e-mail, they said they were working on it.

In the meantime you should be able to use either `remotes::install_github` to install first from `leeper/prediction`, then `leeper/margins`, then `fsolt/dotwhisker`, **or** use `remotes::install_version()` to install the last-archived versions of the corresponding packages from CRAN ...

**Comment by LucieCBurgess** [comment]
Thank you, that's very helpful

**Comment by sammo3182** [comment]
> Thank you, that's very helpful - I had already tried remotes::install_version() but it failed due to the missing margins package. Will give these instructions a try.

Just submit the new version to CRAN. Have a try to install from there, @LucieCBurgess . Let me know if there's any problem. 

Sorry for not addressing this issue sooner...

**Comment by sammo3182** [comment]
Apparently, I missed the last email from Thomas Leeper with Ben ... My bad.

And sorry, @LucieCBurgess, it looks like we need to wait for Thomas to update the upstream package `margin` to restore the package. 

If he still cannot release the new `margin` in a month or so, I will figure out how to switch  to `margineffect`-based function as Ben suggested.

**Comment by bbolker** [comment]
In private e-mail Thomas said he had been busy with personal stuff but was hoping to re-submit `margins` shortly.

**Comment by Rainjie-afk** [comment]
@bbolker Thanks for you advise,  `remotes::install_github('fsolt/dotwhisker')` is just fine for me to install dotwhisker(Version 0.8.99)
