### ISSUE TITLE
Vignette: note that intercept cofficients are often not interesting and can be omitted from plots

### ISSUE THREAD

**Issue by fsolt** [fsolt/dotwhisker#15]
per Kastellec and Leoni 2007, 765.  Just drop that row from your tidy data.frame : df %>% filter(term!="(Intercept)") %>% dwplot...

**Comment by sammo3182** [comment]
shouldn't we leave this judgement to the users?

**Comment by fsolt** [comment]
exactly.  But note in the vignette that that's an option for them

**Comment by sammo3182** [comment]
noted this argument in d3ec8c0478abc9b135ef841e6754ffea535434dc
