### ISSUE TITLE
dwplot: deal with models with differing variables

### ISSUE THREAD

**Issue by fsolt** [fsolt/dotwhisker#16]
Hu says (#2): The way only adding observation in "term" doesn't work, because ggplot codes need to calculate "estimate - qnorm(.975) * std.error".

A potential solution is to calculate the upper and lower bounds of CI before plotting and avoid calculations in the ggplot codes.

**Comment by sammo3182** [comment]
the problem is fixed in d3ec8c0478abc9b135ef841e6754ffea535434dc
working on adding an argument for multiple CI choices (99%,95%,90%)
