### ISSUE TITLE
 warning message in by_2sd

### ISSUE THREAD

**Issue by sammo3182** [fsolt/dotwhisker#17]
In every time's package building, there is a warning message caused by by_2sd:

replacing previous import by ‘magrittr::%>%’ when loading ‘dotwhisker’ 

How should we explain it, if this is unavoidable?

**Comment by fsolt** [comment]
this has to do with loading dplyr after magrittr (which we end up doing because various functions load both, even though each one loads dplyr first then magrittr).  Perhaps you can figure out a way to consolidate the dependencies?

**Comment by sammo3182** [comment]
fixed by 8680aba66d0038ce9ce54e52fb97aba4a1fc17e0
