### ISSUE TITLE
Vignette: include example of plotting models with different variables

### ISSUE THREAD

**Issue by fsolt** [fsolt/dotwhisker#2]
Have to add an observation to the df with the variable name but otherwise NA (I think)

**Comment by sammo3182** [comment]
The way only adding observation in "term" doesn't work, because  ggplot codes need to calculate "estimate - qnorm(.975) * std.error".

A potential solution is to calculate the upper and lower bounds of CI before plotting and avoid calculations in the ggplot codes.

**Comment by sammo3182** [comment]
fixed by cdfac4a32f0980518c4dbcf1487a620861a21f5d
