### ISSUE TITLE
Vignette: include example of "secret weapon"

### ISSUE THREAD

**Issue by fsolt** [fsolt/dotwhisker#3]
Per http://andrewgelman.com/2005/03/07/the_secret_weap/

```{r}
# The "Secret Weapon" (plot one coefficient for many models)
data(diamonds)

by_clarity <- diamonds %>% group_by(clarity) %>% 
    do(tidy(lm(price ~ carat + cut + color, data = .))) %>% rename(model=clarity) 

carat_results <- by_clarity %>% filter(term=="carat") %>% select(-term) %>% 
    rename(term=model) 

dwplot(carat_results) + 
    xlab("Estimated Coefficient (Dollars)") + ylab("Diamond Clarity") + 
    ggtitle("Estimated Coefficients for Diamond Size Across Clarity Grades") +
    theme(plot.title = element_text(face="bold"), 
          legend.position = "none")
```

**Comment by sammo3182** [comment]
Sortof relating to that, do we really want to limit the number of models for comparison? Of course, technically, there will be issues to create "shifts" with varying numbers, but it should be solvable by embedding some arithmetic progressions.

**Comment by fsolt** [comment]
I’ve been wondering the same thing, or at least whether the limit on models should be higher.  The limit on the (maximum) shift is really ~.33, because if it’s more than that a variable's top model is farther from its center line than it is from the bottom model of the next variable.

Not really related to the secret weapon, though; the example above has a whole bunch of models in it.  In the secret weapon, models and variables essentially change places.

**Comment by sammo3182** [comment]
ah... doesn't a maximum boundary actually make things easier? something like like seq(.05, .33, length.out = n_model) ? we may also adjust the dot size to make the plots with more than 3 models clearer. I can work on that after finishing the first draft of the vignette, if you don't have much free time on it.

**Comment by fsolt** [comment]
good thought.  seq(-dodge_size, dodge_size, length.out=n_model) should do the trick.  I fussed with dot sizes a bit--as far as I can tell they can't be made smaller than the default size (which is 1).

**Comment by fsolt** [comment]
Oh, and I'll leave the implementation to you for when you've finished the vignette.  I'm working on #7

**Comment by fsolt** [comment]
^^ Actually should be seq(dodge_size, -dodge_size, length.out=n_model) so first listed model is on top

**Comment by sammo3182** [comment]
add an example and a citation in the vignette.
