### ISSUE TITLE
Confidence intervals using `lb` and `ub` do not work

### ISSUE THREAD

**Issue by SteveLane** [fsolt/dotwhisker#38]
Using the cars example, suppose we put all models into the one df:
```{r}
allM <- bind_rows(cbind(tidy(m1), confint(m1), model = "M1"), cbind(tidy(m2), confint(m2), model = "M2"), cbind(tidy(m3), confint(m3), model = "M3"))
```
Plotting this using the default works fine:
```{r}
dwplot(allM)
```
But if we remove the `std.error` column, and rename the lower and upper bounds:
```{r}
allM2 <- allM %>% select(-std.error) %>% rename(lb = `2.5 %`, ub = `97.5 %`)
```
Then plotting no longer works:
```{r}
dwplot(allM2)
```

Tested using the CRAN version, on CentOS7.

**Comment by fsolt** [comment]
Thanks, Steve; especially for the reprex!  Working on this now.

**Comment by fsolt** [comment]
If you reinstall using `devtools::install_github("fsolt/dotwhisker")` you should be all set, Steve.  It was a silly bug; thanks for catching it.  :D

**Comment by SteveLane** [comment]
Great - thanks. Easy fixes are great :)
