### ISSUE TITLE
stretched x axis

### ISSUE THREAD

**Issue by sammo3182** [fsolt/dotwhisker#48]
The x axis in the secrete weapon is always stretched out to the whole width. I ran the example in the vignette, the result was stretched to the entire plot zone.  I tried to use arguments of expand, limits, breaks, etc. in scale_x_continuous to fix the problem. But none of them succeeded.

**Comment by fsolt** [comment]
Is this still a problem or is it fixed now?  Looking at some secret weapon plots using the current build, I don't see an issue
