### ISSUE TITLE
Vignette: include example of standardizing by multiplying coefs by 2 std.deviations

### ISSUE THREAD

**Issue by fsolt** [fsolt/dotwhisker#5]
Only for ordinal/continuous IVs (not for dichotomous IVs).  Equivalent to dividing IVs by 2 sd, as advocated by:

Gelman, Andrew. 2008. Scaling regression inputs by dividing by two standard deviations. Statistics in Medicine, 27:2865–2873.

Of course, this is just done in the df before passing it to function.

**Comment by sammo3182** [comment]
fixed an error in the example of it. Also, what's the superiority of it to Gelman's arm::standardize?

**Comment by fsolt** [comment]
two differences:
1. most importantly, it works on tidy dataframes of results instead (a limited number of) model objects
2. it doesn't include cluttery options

**Comment by fsolt** [comment]
Good point, though: I'll add a @seealso to the documentation

**Comment by sammo3182** [comment]
Another issue for by_2sd is producing NAs for intercept. should we ask by_2sd automatically jump over the first row every time? But the problem becomes messier for ordered logit or multinomial outputs.

**Comment by fsolt** [comment]
good point, it actually brings up three issues: #13, #14, #15

**Comment by sammo3182** [comment]
all issues are fixed in 9229da81828a3ee998dcaab82364834eaafa4d13
