### ISSUE TITLE
extention to `polr`

### ISSUE THREAD

**Issue by sammo3182** [fsolt/dotwhisker#64]
Just noticed Ben's succinct way to apply `tidy` on `polr` results (tidyverse/broom#38). It suggests we can enable `dwplot` to present `polr` results with only two lines of commands prior to calling `tidy` in `dwplot`:

```r
family.polr <- function(object,...) NULL
tidy.polr <- broom:::tidy.lm
```
That looks a useful extension, isn't it?

**Comment by fsolt** [comment]
Sure.  Give it a try.  If it works, think about adding a bit to the vignette (and perhaps other docs) to alert users that it's there?

**Comment by fsolt** [comment]
Think you'll be able to get to this this week?  If not, I think we're ready to push an update to CRAN.  If so, go ahead and then update.

**Comment by sammo3182** [comment]
There's still a problem of using `:::` according to the RCMD check. Thinking to copy the function directly to avoid the warning (referring to floybix/latticist#9)
