### ISSUE TITLE
`polr` result cannot normally pass through

### ISSUE THREAD

**Issue by sammo3182** [fsolt/dotwhisker#75]
Problem comes from the `dw_tidy` function to replicate 

```
family.polr <- function(object,...) NULL
tidy.polr <- broom:::tidy.lm
```
without `broom:::`

**Comment by fsolt** [comment]
Is the issue that `broom::tidy()` doesn't yet support `polr`?  The only current mention I find of `polr` in `tidyverse/broom` is [here in the tidier for `rstanarm` output](https://github.com/tidyverse/broom/blob/e0f7afd2ab6ccc96f421e7cfc0a2c178a6b0ac66/R/rstanarm_tidiers.R).  If that's right, I suggest that the `polr`-tidying code in `dw_tidy` shouldn't really be there at all, but instead should be drafted for submission to `broom`.
