### ISSUE TITLE
enhancement request: allowing different colors for the dots and the whiskers

### ISSUE THREAD

**Issue by IndrajeetPatil** [fsolt/dotwhisker#81]
Is there any way to change the color of both `dot` and the `whisker` separately? 
This is something I can do with `GGally::ggcoef`, but I much prefer using `dotwhisker` package and so it would be lovely if you can implement this.

I am providing a minimal example below:

``` r

# loading the library
library(dotwhisker)
#> Loading required package: ggplot2
library(GGally)

# linear model of interest
lm_object <- stats::lm(formula = wt ~ am * cyl, data = mtcars)

# creating the plot with dwplot
dotwhisker::dwplot(
  x = lm_object,

  dot_args = list(color = "red"),
  # color for the dot
  line_args = list(color = "black")   # color for the whisker
) +
  ggplot2::geom_vline(
    xintercept = 0,
    colour = "grey60",
    linetype = 2,
    size = 1
  )
```

![](https://i.imgur.com/RRsHoi2.png)

``` r

# creating the plot with ggcoef
GGally::ggcoef(x = lm_object,
               exclude_intercept = TRUE,
               color = "red",
               errorbar_color = "black")
```

![](https://i.imgur.com/9YLUaha.png)

Created on 2018-06-09 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by fsolt** [comment]
Okay, the development version does this now by reintroducing the whisker_args argument, which we had for a while but dropped at some point.  (Note that line_args is just for `style = "distribution"`.  I suppose it could do double duty for both styles, but I think I'll keep the two separate.) As soon as I confirm it all works fine with the newest ggplot2, I'll get it up on CRAN.

``` r
# loading the library
library(dotwhisker)
#> Loading required package: ggplot2

# linear model of interest
lm_object <- stats::lm(formula = wt ~ am * cyl, data = mtcars)

# creating the plot with dwplot
dwplot(x = lm_object,
       dot_args = list(color = "red"), # color for the dot
       whisker_args = list(color = "black"),   # color for the whisker
       vline = ggplot2::geom_vline(xintercept = 0,  # put vline _behind_ coefs; see https://github.com/fsolt/dotwhisker/issues/84
                                   colour = "grey60",
                                   linetype = 2,
                                   size = 1))
```

![](https://i.imgur.com/k3r6as3.png)

Created on 2018-06-27 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by brandybiggar** [comment]
fsolt is this available now? I'm trying to use it but not having any luck
