### ISSUE TITLE
ordering doesn't work with more than one regression

### ISSUE THREAD

**Issue by chr1swallace** [fsolt/dotwhisker#85]
If I use order_vars with a list of regressions, only the first gets plotted.  I think that's because in this line in dwplot, match() selects the first match https://github.com/fsolt/dotwhisker/blob/2f5fa24235662baf34e4173ab41e9eaee029d5e2/R/dwplot.R#L132

I think this is fixed by replacing the line with 
```
df <- df[order(df$term),]
```

**Comment by fsolt** [comment]
Issue confirmed:
``` r
library(dotwhisker)
#> Loading required package: ggplot2

m1 <- lm(mpg ~ wt + cyl + disp + gear, data = mtcars)
m2 <- update(m1, . ~ . + hp) # add another predictor
m3 <- update(m2, . ~ . + am) # and another 

dwplot(list(m1, m2, m3), order_vars = c("cyl", "disp", "gear", "wt", "am", "hp"))
```

![](https://i.imgur.com/foL6jBl.png)

Created on 2018-07-03 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by chr1swallace** [comment]
Thanks for checking!  With https://github.com/chr1swallace/dotwhisker seems fixed:

![image](https://user-images.githubusercontent.com/2189544/42220799-faf8ced0-7ec7-11e8-8ffa-dea0d512e636.png)

**Comment by fsolt** [comment]
And your fix works:
``` r

library(dotwhisker)
#> Loading required package: ggplot2

m1 <- lm(mpg ~ wt + cyl + disp + gear, data = mtcars)
m2 <- update(m1, . ~ . + hp) # add another predictor
m3 <- update(m2, . ~ . + am) # and another 

dwplot(list(m1, m2, m3), order_vars = c("cyl", "disp", "gear", "wt", "am", "hp"))
```

![](https://i.imgur.com/G6QZOGv.png)

Created on 2018-07-03 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by fsolt** [comment]
Thanks, Chris!  I appreciate your help with this!
