### ISSUE TITLE
order_vars not working with lmer models?

### ISSUE THREAD

**Issue by misea** [fsolt/dotwhisker#94]
In version 0.5.0 this seems to work fine:

`dwplot(lmer(mpg~hp+wt+(1|cyl), data=mtcars))`

But this yields a plot with axes but no data/ticks

`dwplot(lmer(mpg~hp+wt+(1|cyl), data=mtcars), order_vars = c('wt', 'hp', 'sd__(Intercept)', 'sd__Observation'))`

I have tried order_vars without the sd__ variables, but to no avail. It's a straightforward workaround to arrange a tidy dataframe, but wanted to report issue, or find out if I'm misunderstanding the correct usage.

**Comment by sammo3182** [comment]
I can't replicate your issue. The plot looks fine in my side. Perhaps just try the dev version? Let me know if there's still a problem

```r
library(dotwhisker)
library(lme4)

dwplot(lmer(mpg~hp+wt+(1|cyl), data=mtcars), order_vars = c('wt', 'hp'))
```

> In version 0.5.0 this seems to work fine:
> 
> `dwplot(lmer(mpg~hp+wt+(1|cyl), data=mtcars))`
> 
> But this yields a plot with axes but no data/ticks
> 
> `dwplot(lmer(mpg~hp+wt+(1|cyl), data=mtcars), order_vars = c('wt', 'hp', 'sd__(Intercept)', 'sd__Observation'))`
> 
> I have tried order_vars without the sd__ variables, but to no avail. It's a straightforward workaround to arrange a tidy dataframe, but wanted to report issue, or find out if I'm misunderstanding the correct usage.

**Comment by sammo3182** [comment]
I'll close the issue since there's been no further feedback for a long time. Free to reopen it if the mentioned problem still bothers you. A replicable example will be very helpful. Thanks!
