### ISSUE TITLE
Changing font and axis scale in dwplot()

### ISSUE THREAD

**Issue by Jakub-42** [fsolt/dotwhisker#97]
Hi,

I don't know  why theme(text = element_text(family = font)) doesn't work for dwplot when it is based on ggplot2.

Also, I would like to ask how I can set x-axis scale in dwplot().

Many thanks,

Jakub

**Comment by sammo3182** [comment]
Do you have a replicable example for your issue. the font works well in my side.

```r
library(dotwhisker)

m1 <- lm(mpg ~ wt + cyl + disp + gear, data = mtcars)
dwplot(m1) +
  theme(text = element_text(size = 16, family = "serif")) 
```

![image](https://user-images.githubusercontent.com/6463211/107868804-45e0c000-6ec2-11eb-8a76-fccaec71324b.png)

And you adjust the scale  of the x axis just as you do with `ggplot` through functions such as `xlim`
